/* eslint-disable no-var */
/**
 * @see https://developer.ones.cn/docs/guide/advanced/storage
 * @summary ones.d.ts is generated by `op format` cli commands.
 * DO NOT MODIFY MANUALLY
 */
declare var ONESEntities: {
    approval_config: {
        attributes: {
            team_uuid?: string;
            approval_project_uuid?: string;
            issue_type_uuid?: string;
            approved_status_uuid?: string;
            approved_status_name?: string;
            template_uuid?: string;
        };
        indexes: null;
    };
    approval_record: {
        attributes: {
            issue_uuid?: string;
            team_uuid?: string;
            event_id?: string;
            status?: string;
            project_uuid?: string;
            project_name?: string;
            error_code?: string;
            error_message?: string;
            retry_count?: number;
            updated_at?: number;
        };
        indexes: null;
    };
};
