/* eslint-disable no-var */
/**
 * @see https://developer.ones.cn/docs/guide/advanced/storage
 * @summary ones.d.ts is generated by `op format` cli commands.
 * DO NOT MODIFY MANUALLY
 */
declare var ONESEntities: {
    announcement: {
        attributes: {
            team_uuid?: string;
            project_uuid?: string;
            title?: string;
            content_html?: string;
            attachments_json?: string;
            status?: string;
            creator_uuid?: string;
            creator_name?: string;
            audience_type?: string;
            is_pinned?: boolean;
            created_at?: number;
            published_at?: number;
            updated_at?: number;
        };
        indexes: null;
    };
    announcement_audience: {
        attributes: {
            announcement_id?: string;
            team_uuid?: string;
            project_uuid?: string;
            user_uuid?: string;
            user_name?: string;
            created_at?: number;
        };
        indexes: null;
    };
    announcement_read: {
        attributes: {
            announcement_id?: string;
            team_uuid?: string;
            project_uuid?: string;
            user_uuid?: string;
            user_name?: string;
            first_read_at?: number;
            last_read_at?: number;
        };
        indexes: null;
    };
};
